jobs:
  deploy:
    docker:
      - image: cimg/base
    steps:
      - attach_workspace:
          at: my-site
      - run: ls -lah my-site
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the hugo-orb
  hugo: circleci/hugo@0.2
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "main"
  main:
    # Run the main/run job in its own container
    jobs:
      - hugo/build:
          html-proofer: true
          source: /
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - hugo/build